### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by mouawiya** [maudzung/Complex-YOLOv4-Pytorch#42]
i've tried the code on a computer with graphic card GTX 1050 Ti and i still got the Cuda out of memory error, when i tried to lowed the batch size, it worked for a moment then stopped as it is showed in the picture below
![image](https://user-images.githubusercontent.com/89226952/169004326-015f2cc9-e12e-4e7b-afd4-31c4c7685dd6.png)

**Comment by tanay-o** [comment]
Hey! got the same error, try reducing the batch size when you train your dataset with the --batch_size parameter (default 4), that worked for me.
